sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
cache:
  directories:
  - node_modules
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
script:
- npm run build:prod
deploy:
  node_js: '12'
  skip_cleanup: true
  on:
    branch: release/*
  provider: npm
  email: developer@uiza.io
  api_key:
    secure: Z+4fAeJPHnGiq/TDpa2uetduraX5WzUY7dT5UTBiKrgPME52Q1QNfoARDXs+Mz/kCbqOdDvCsY9o2d6P4eLF/V0rVdhlEn8M1lBdcLkvkyAmx+PwnofVsokYeye1qwwVjy8VJIcxOUJPAUVNB1w/tZuoDAyZ0CyGJQOU8/LkQVQdMqeKXOBQQT81Z7SqroEC+v4icT38stQisUFxM8kd9V5UY0tUTz7BJhp1qY84a5TsUXBp+GyVt/Ec54dkvVBm5Y/bLy1qrd4UQwVRhtu8lbEF/s5tqveP84rx8WchaT7wxLsHPKeiC15xuwre3x80vXoZmTANjHqCiNOaRcPX+r59tMvqeDT1NImGnf7Cp4YGduzRpCUtBpfCHQ57jd99/Mc57EIyZEu5QFeV3S8KLYDV6qouRoh+TvD9sUFtZbBkkmOU0wnPsZelLNCaeN40OKCY/HSDbsVd1q24Aum/I3oIVWDnzrgUVjODGaVZQ9C40cd37aPY15rpS1hQT15Yw7HezT5yhyhjPSK8+KLcI1EuB9eHWc66xKbJo6+jWgIGdrNbA58+d98lE6Sea3/uIdGQx6xx7ZDhvvj+GnfY4cau0Nmtq/N2buAq2VNp2ZsSxBAbHxrOEwOVfamTVHn9gZTVJi+CYUx40SK7vR3LN8hMzwKma/fQ8al/B45XvHk=
notifications:
  slack:
    secure: SQJkIhHTiX6Ls5u7eajm1PqsOnWQ8dclxsKFY5aUuuxWSHG0/R6tEvyktelAOhBQKZ1p8B4gWs4HjbDRWh5SeogytOyAvrhKJaX0+DG+eJoHOVBD8xzow/p4Gj6u9bMwlWYc+uj8WnJPMqYcx2lciWIL156CEsd/CbnvFQOlA2hdMH+gLd46nb4bBHc2YS6qC6YHqvsSZPiMLaPo8hk/LDZeMC3+g0oChLRyJIaC5bIh17lVAgTccbYy4jBooM3ryckYnVZvhKlAPfgZ8bP/kXia7FMkOi8vhtoi3V8pekif44ii4CfQg3+QEpn9cGSHfBrveIvqOAwribdh4YvqAOfviapbGnJBtsfX3L/rlCYfUirfhEJ6Njz9zKpTo7yafdvndd/47zkKz3cNzpyrodIqG24DIsB700Gphyss9s95rf68dItKME9ZlGxRTBGbI+J33FvEfAnCHhxB8bFnWQYc/GIXd06jhHVSXgugBesNgeZYuKt1k3UP8L7x4DK/Yk+q3ZGHktOmNbESw5LK8D1E/elvhqM4SgitTtVvi+d/9fMUlTdcxRPUGqH87Bt285eWUlWyGlpKECBhcs0Y2XOukkw3pszUBVugAaueppFj/pJJt0a9zYTZHCr8tmJCKYY3wK3uvnpsVLb19vIwUybQ5xbsCpu9y4SVvjRurxA=
